//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecipeAPIEntities : DbContext
    {
        public RecipeAPIEntities()
            : base("name=RecipeAPIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Version> Versions { get; set; }
        public DbSet<ErrorLog> ErrorLogs { get; set; }
        public DbSet<Ingredient> Ingredients { get; set; }
        public DbSet<IngredientList> IngredientLists { get; set; }
        public DbSet<Instruction> Instructions { get; set; }
        public DbSet<InstructionList> InstructionLists { get; set; }
        public DbSet<Measurement> Measurements { get; set; }
        public DbSet<Recipe> Recipes { get; set; }
        public DbSet<Member> Members { get; set; }
    }
}
